### PR TITLE
[WIP] App bootstrapper refactoring

### PR DESCRIPTION
**Pull request by mauroservienti**
Connects to #21, this PR adds support for the new simplified ApplicationBoostrapper model.

@micdenny please review.

### CODE REVIEW

**Comment by mauroservienti** [comment]
@micdenny Why the build failure?

**Comment by mauroservienti** [comment]
this should now be ready to be merged, however I'd like to address https://github.com/RadicalFx/housekeeping/issues/35 before, @micdenny thoughts?

**Comment by mauroservienti** [comment]
I'll rebase this one on develop before moving forward.

**Comment by mauroservienti** [comment]
I renamed this to WIP, we still have a dependency on https://github.com/RadicalFx/Radical/pull/209 that is done but not released anywhere yet.

**Comment by mauroservienti** [comment]
rebased on develop, checked that all the dependencies are released at least on `myget`, so @micdenny this can be reviewed and merged.

**Comment by micdenny** [comment]
ok great, I'm on it now

**Comment by micdenny** [comment]
what about having a couple of static factory methods in the `Topics.Radical.ApplicationBootstrapper` class?

``` csharp
        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="TShellType"></typeparam>
        /// <returns></returns>
        public static ApplicationBootstrapper Boot<TShellType>() where TShellType : Window
        {
            var bootstrapper = new ApplicationBootstrapper<TShellType>();
            bootstrapper.UsingAsContainerBootstrapper(new Windows.Presentation.Boot.PuzzleContainerBootstrapper());
            return bootstrapper;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="shellViewType"></param>
        /// <returns></returns>
        public static ApplicationBootstrapper Boot(Type shellViewType)
        {
            var bootstrapper = new ApplicationBootstrapper();
            bootstrapper.UsingAsContainerBootstrapper(new Windows.Presentation.Boot.PuzzleContainerBootstrapper());
            return (ApplicationBootstrapper)bootstrapper.UsingAsShell(shellViewType);
```

so the developer has only to remember one thing `ApplicationBootstrapper` then hit the dot and is on the way to Radical :smile:

this gives also a couple of improvements, from the main method you can avoid the explicit instantiation of the bootstrapper, so you don't get `local variable is never used` nor `possible unassigned object creation by new expression`, when you don't need the returned object:

``` csharp
        public App()
        {
            ApplicationBootstrapper.Boot<MainView>();
        }
```

it also avoid calling a virtual method inside a constructor:

image

thoughts?

**Comment by micdenny** [comment]
you can check a DRAFT from my repo: https://github.com/RadicalFx/Radical.Windows.Presentation/compare/app-bootstrapper-refactoring...micdenny:app-bootstrapper-refactoring

**Comment by mauroservienti** [comment]
isn't this addressed by https://github.com/RadicalFx/Radical.Windows.Presentation/issues/22?
What do we need to take into account to be sure we can implement https://github.com/RadicalFx/Radical.Windows.Presentation/issues/22?

**Comment by micdenny** [comment]
> isn't this addressed by #22?
> What do we need to take into account to be sure we can implement #22?

:notes: "I'm going slightly mad..." :smile: 

yes, you're right I already discussed this with you and completely forgot.... ok then **is this a non-breaking feature** isn't it? if yes, we can merge this and re-iterate later on #22, because this merge is needed by #22 to proceed anyway.

**Comment by mauroservienti** [comment]
yes, I'll rebase and move forward. Thanks.

In order to avoid calling a `virtual` member from the `.ctor` what if we make the class `sealed` and remove all the `virtual` members? In the end with the new model (https://github.com/RadicalFx/Radical.Windows.Presentation/issues/22) there should be no requirements at all to inherit from this, since this will behave as a mere entry point, and we can always change our mind in the future without introducing a breaking change.

**Comment by micdenny** [comment]
> In order to avoid calling a virtual member from the .ctor what if we make the class sealed and remove all the virtual members?

agreed! probably could become `static` as well, so to now it's ok `sealed`

**Comment by mauroservienti** [comment]
Marked as WIP since the more I work on this the more I think that we can improve it, once pushed I'll try to summarize my ideas

**Comment by mauroservienti** [comment]
take a look @micdenny now it is a static factory :smile: so it address #22 as well. The more I look at it the more I think that

```
public IContainerBootstrapper ContainerBootstrapper { get; private set; }
```

smells... :disappointed:, I don't remember why I needed it, I'll check. Maybe I should try to address https://github.com/RadicalFx/housekeeping/issues/34 first and see what happens to the design of this one.

**Comment by micdenny** [comment]
> Maybe I should try to address RadicalFx/housekeeping#34 first and see what happens to the design of this one.

yes, probably first it is better to develop the new static entry point, but that is what you probably achieved with the latest changes here, take a look at [`RabbitHutch`](https://github.com/EasyNetQ/EasyNetQ/blob/31d159c63a8998e210ce9bc50ca75dacc49ad19e/Source/EasyNetQ/RabbitHutch.cs) that is the entry point of EasyNetQ, in fact it's now really similar to what you did on the last changes of `ApplicationBootstrapper`

**Comment by mauroservienti** [comment]
This has been merged into Radical.Windows via https://github.com/RadicalFx/Radical.Windows/pull/111, closing.

**Pull request closed without merging**
