### PR TITLE
Release/1.11.0

### PR DESCRIPTION
**Pull request by mauroservienti**
Connected to https://github.com/RadicalFx/housekeeping/issues/57
@micdenny please review and merge if OK.

### CODE REVIEW

**Comment by micdenny** [comment]
merged, let's see if everything works as expected...

**Comment by micdenny** [comment]
@mauroservienti something went wrong:

image

**Comment by mauroservienti** [comment]
I cannot spot anything wrong in the build log

**Comment by mauroservienti** [comment]
:cry: https://github.com/NuGet/Home/issues/2648#issuecomment-217138686

**Comment by mauroservienti** [comment]
@micdenny we are [still blocked](https://github.com/NuGet/Home/issues/2648#issuecomment-222011908), with most build failing. Do you know if there is any way to force `AppVeyor` to use a specific `Nuget` version or for us to include a specific `Nuget.exe` in our solutions?

**Comment by micdenny** [comment]
I think we can insert the nuget.exe into git for instance under a folder called `tools`, then use it here:

```
  before_build:
    - nuget restore "src\Radical.Windows.Presentation.sln"
```

specifying the relative path `tools\nuget.exe` so:

```
  before_build:
    - tools\nuget.exe restore "src\Radical.Windows.Presentation.sln"
```

it should works

**Pull request merged**
