### PR TITLE
Release-1.11.0

### PR DESCRIPTION
**Pull request by mauroservienti**
Release-1.11.0. Connects to https://github.com/RadicalFx/housekeeping/issues/57
Goal of this release is to:

- start embracing SemVer adding dependencies ranges
- update deps to latest stable
- force nuget version to prevent CI failures (hopefully)

### CODE REVIEW

**Comment by mauroservienti** [comment]
oh yeah, build is green. @micdenny please, pretty please 😄, review and hit that button!

**Review by micdenny — APPROVED** [review]
that's ok to me

**Comment by micdenny** [comment]
@mauroservienti we have to push a tag, isn't it?

**Comment by micdenny** [comment]
> @mauroservienti we have to push a tag, isn't it?

no, the tag is done automagically 😄

**Comment by mauroservienti** [comment]
Yep automatically. Thanks 😄

**Pull request merged**
