### PR TITLE
ApplicationBootstrapper expects the application to have a main view that needs to be opened at startup

### PR DESCRIPTION
**Pull request by mauroservienti**
Connects to #18 
@micdenny can you please review?

### CODE REVIEW

**Comment by micdenny** [comment]
@mauroservienti the code is pretty simple, I will test on my own project just to be sure that everything works as expected

**Comment by micdenny** [comment]
@mauroservienti something went wrong on building, I will also check that

**Comment by mauroservienti** [comment]
Thanks @micdenny, seems that the NuGet restore failed at build time. I pushed the version number change as well (MyGet only at the moment, this PR is against `develop`)

**Comment by mauroservienti** [comment]
build succeeded now :)

**Comment by micdenny** [comment]
> MyGet only at the moment, this PR is against develop

you're right!

> seems that the NuGet restore failed at build time

yes, now the build has completed successfully

will review by testing in on my project, and merge it if everything is fine.

**Comment by mauroservienti** [comment]
cool! thanks

**Comment by mauroservienti** [comment]
@micdenny I need this merged in order to move forward. thanks. Can you please take a look now?

**Comment by micdenny** [comment]
> Can you please take a look now?

:+1: :moneybag: :joy:

**Comment by micdenny** [comment]
give me some minutes more for this, I really want to download it and test it to be sure everything work properly in all my projects, thanks

**Comment by mauroservienti** [comment]
thank you very much for your time, appreciated.

On Fri, Nov 27, 2015 at 12:50 PM, Michael Denny notifications@github.com
wrote:

> give me some minutes more for this, I really want to download it and test
> it to be sure everything work properly in all my projects, thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RadicalFx/Radical.Windows.Presentation/pull/19#issuecomment-160122596
> .

## 

Mauro Servienti

**Comment by micdenny** [comment]
everything's fine, merging

**Comment by mauroservienti** [comment]
wonderful thanks!

**Pull request merged**
