### PR TITLE
Hotfix/1.11.1

### PR DESCRIPTION
**Pull request by mauroservienti**
Connected to https://github.com/RadicalFx/housekeeping/issues/57

tries to fix the build downloading NuGet 3.4.4 RC from an internal support repo.

### CODE REVIEW

**Comment by micdenny** [comment]
probably now we can see if it works without this workaround

**Comment by micdenny** [comment]
as you can see from the test PR #43 now the build is working without any changes

**Comment by mauroservienti** [comment]
this https://github.com/RadicalFx/Radical.Bootstrapper/blob/develop/appveyor.yml#L25 can be a btter approach. Closing.

**Comment by mauroservienti** [comment]
reopening to apply the proposed fix https://github.com/RadicalFx/Radical.Bootstrapper/blob/develop/appveyor.yml#L25

**Comment by mauroservienti** [comment]
wrong one. ooops 😄

**Pull request closed without merging**
