### PR TITLE
Added *.Messaging.Handlers.* to convemtion for command handlers

### LINKED ISSUE #28: Change "*.Messaging.Handlers" to "*.Messaging.Handlers.*" on configuration by convention for message handlers
_From @nazarenomanco on March 7, 2016 12:11_

In order to group better the messages when the number of the messages becomes copious

_Copied from original issue: RadicalFx/Radical#212_

### PR DESCRIPTION
**Pull request by nazarenomanco**
@mauroservienti please check.
Fix #28

### CODE REVIEW

**Comment by nazarenomanco** [comment]
@mauroservienti what's happened?

**Comment by mauroservienti** [comment]
https://github.com/RadicalFx/Radical.Windows.Presentation/issues/27

**Comment by mauroservienti** [comment]
@nazarenomanco can you please update Nuget packages and push again? should be enough to update the `Radical.Windows` dependency to the latest one.

**Comment by nazarenomanco** [comment]
Done! Tell me if it is ok.

**Comment by mauroservienti** [comment]
Build is OK now. Merging. I'll release as soon as we have the new build support in place.

**Pull request merged**
