### PR TITLE
Expose a service as resource

### PR DESCRIPTION
**Pull request by mauroservienti**
Connects to https://github.com/RadicalFx/Radical.Windows.Presentation/issues/49

This PR allows any registered component in the container to be exposed as a resource, services can be resources at the `Application` level:

```
bootstrapper.ExposeAsResource<TService>();
```

or at the `View` level

```
bootstrapper.ExposeAsResource<TService, TView>();
```

If services should be exposed as resources at the View level, resources are injected in the view at view resolution time by the `IViewResolver`.

### CODE REVIEW

**Comment by mauroservienti** [comment]
@micdenny any idea on how to test such a thing?

**Comment by mauroservienti** [comment]
@micdenny ping 😃

**Comment by mauroservienti** [comment]
@micdenny thoughts on this?

**Comment by micdenny** [comment]
we're coupled on the wpf object model so the unit test is hard to accomplish.... 🤔 the only way I see at the moment is to abstract the `Application.Current.Resources` so to be able to unit test `ExposeRegisteredAppResources` and test that the abstracted Application has in fact the Resources dictionary full with the right services we expect.

Something like:

```csharp
public interface IApplication
{
    Dictionary<string, object> Resources { get; }
}
```

and then we can provide a stub:

```csharp
public class ApplicationStub : IApplication
{
    public Dictionary<string, object> Resources { get; } = new Dictionary<string, object>();
}
```

Then we expose the `IApplication` from the `ApplicationBoostrapper` to be able to change it so we can test it with a stub.

This is just a draft idea, but could be a starting point to think about.

**Review by nazarenomanco — APPROVED** [review]

**Comment by mauroservienti** [comment]
This needs to be recreated in Radical.Windows as soon as https://github.com/RadicalFx/Radical.Windows/pull/111 is merged

**Comment by mauroservienti** [comment]
Replaced by https://github.com/RadicalFx/Radical.Windows/pull/130

**Pull request closed without merging**
