### PR TITLE
trying to force nuget version

### PR DESCRIPTION
**Pull request by mauroservienti**
Connected to https://github.com/RadicalFx/housekeeping/issues/57

let's see what happens

### CODE REVIEW

**Comment by mauroservienti** [comment]
@micdenny [manually forcing](https://github.com/RadicalFx/Radical.Windows.Presentation/pull/40#issuecomment-222060913) the `Nuget` version to the latest 3.4.4-RC works. What should we do?

Options:
- wait for 3.4.4 to be officially released and AppVeyor to update it
- ship our own version, in which case I'd close this PR and start an hotfix since [1.11.0](https://github.com/RadicalFx/Radical.Windows.Presentation/pull/40) is merged and the only step missing is the release

**Comment by micdenny** [comment]
that's exactly what I've suggested in #40 and I was suggest also to use it while restoring, but that's not mandatory

could be better to move the `nuget.exe` under `tools` folder instead of `src`?

**Comment by micdenny** [comment]
another way could be to download it directly from another source using powershell, this avoid to push an .exe file to the git database that will increase the db footprint forever.

**Comment by mauroservienti** [comment]
all good suggestions, I'll close this one, create an `hotfix` branch, add `nuget` downloaded via a PS script and create a new PR.

**Pull request closed without merging**
